@startuml core

scale 0.7

!define EntityType class
!define IdType Field
!define EnumType enum
!define RelatedType "1..1"
!define ForeignKeyType "1..*"

package "core" {

    EntityType Personne {
        +nom: CharField
        +prenom: CharField
        +sexe: CharField
        +date_naissance: DateField
        +pays: ForeignKey(Pays)
        +document_identification: OneToOneField(DocumentIdentification)
        +tel: CharField
        +email: EmailField
        +age(): int
    }

    EntityType Client  {
        +appartenance: ForeignKey(Organisation)
    }

    EntityType Organisation  {
        +designation: CharField
        +abbr: CharField
        +contact: CharField
    }

    EntityType DocumentIdentification  {
        +num_doc: CharField
        +type_document: CharField
        +num_id: CharField
        +date_delivrance: DateField
        +valide_jusqua: DateField
        +autorite: CharField
    }

    EntityType Pays {
        +nom: CharField
        +abbr: CharField
        +code: CharField
    }

    EntityType TypeService {
        +designation: CharField
    }

   EntityType  Service {
        +type: ForeignKey(TypeService)
    }

    EntityType Classe {
        +designation: CharField
    }

    EntityType ServiceClasse {
        +classe: ForeignKey(Classe)
        +service: ForeignKey(TypeService)
        +prix: FloatField
    }

    Client -up-|> Personne
    Personne }-up-o DocumentIdentification
    Personne }-up-o Pays
    Client }--o Organisation
    Service }-up-o TypeService
    ServiceClasse }--o Classe
    ServiceClasse }--o TypeService

}

@enduml
