# Generated by Django 4.2.4 on 2023-08-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pays_autorite_remove_pays_date_delivrance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentidentification',
            options={'verbose_name_plural': "documents d'identification"},
        ),
        migrations.AlterModelOptions(
            name='pays',
            options={'verbose_name_plural': 'pays'},
        ),
        migrations.AddField(
            model_name='personne',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='courrier éléctronique'),
        ),
        migrations.AddField(
            model_name='personne',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='documentidentification',
            name='type_document',
            field=models.CharField(choices=[('CN', 'Carte ID Nationale'), ('PS', 'Passport'), ('PC', 'Permis de Conduire')], max_length=2, verbose_name='type du document'),
        ),
    ]
