# Generated by Django 4.2.4 on 2023-09-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_personne_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceclasse',
            name='service',
            field=models.CharField(choices=[('HBG', 'Hébergement'), ('ACL', 'Accueil'), ('RST', 'Restauration'), ('TSP', 'Transport'), ('DVR', 'Divers')], max_length=3, verbose_name='type de service'),
        ),
    ]
