# Generated by Django 4.2.4 on 2023-09-02 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_typeservice_alter_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_naissance',
            field=models.DateField(default=datetime.date(2005, 9, 2), verbose_name='date de naissance'),
        ),
    ]
