# Generated by Django 4.2.4 on 2023-09-30 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_personne_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_naissance',
            field=models.DateField(default=datetime.date(2005, 9, 30), verbose_name='date de naissance'),
        ),
    ]
