# Generated by Django 4.2.4 on 2023-09-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_personne_date_naissance'),
        ('hebergement', '0008_remove_salle_id_salle_service_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.service')),
                ('designation', models.CharField(max_length=25, verbose_name='désignation')),
            ],
            bases=('core.service',),
        ),
        migrations.CreateModel(
            name='ReservationRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(default=0)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.reservation', verbose_name='réservation')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restauration.restaurant', verbose_name='restaurant')),
            ],
        ),
    ]
