# Generated by Django 4.2.4 on 2023-08-31 19:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_documentidentification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.personne')),
                ('reference', models.CharField(max_length=1000, verbose_name='référence')),
                ('contact', models.CharField(max_length=1000, verbose_name='contact')),
            ],
            bases=('core.personne',),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=1000, verbose_name='ID de réservation')),
                ('statut', models.CharField(choices=[('B', 'Brouillon'), ('C', 'Confirmée'), ('T', 'Terminée'), ('O', 'Check-out')], default='B', max_length=1)),
                ('nbr_adultes', models.PositiveSmallIntegerField(verbose_name="nombre d'adultes")),
                ('nbr_enfants', models.PositiveSmallIntegerField(verbose_name="nombre d'enfants")),
                ('date_commande', models.DateField(default=datetime.datetime(2023, 8, 31, 19, 3, 30, 70887, tzinfo=datetime.timezone.utc), verbose_name='date de la commande')),
                ('a_travers', models.CharField(choices=[('S', 'Sur Site'), ('W', 'Le Site Web'), ('A', 'Une Agence'), ('O', 'Autres')], default='S', max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_effectuees', to='hebergement.agent')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.personne', verbose_name='demandeur de réservation')),
            ],
        ),
    ]
