# Generated by Django 4.2.4 on 2023-08-31 22:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_classe_service_serviceclasse'),
        ('hebergement', '0004_reservation_pickup_alter_reservation_date_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.service')),
                ('num', models.CharField(max_length=25, verbose_name='numéro de chambre')),
                ('type_chambre', models.CharField(choices=[('IDV', 'Individuelle (1 lit)'), ('DXL', 'Double (2 lits)'), ('DLS', 'Double (2 lits séparés)'), ('SUT', 'Suite')], max_length=3, verbose_name='type de chambre')),
                ('info_sup', models.TextField(blank=True, null=True, verbose_name='Informations Supplémentaires')),
            ],
            bases=('core.service',),
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=25, verbose_name='désignation de la salle')),
                ('type_salle', models.CharField(choices=[('CFR', 'Conférences'), ('FET', 'Fêtes'), ('AUD', 'Auditorium')], max_length=3, verbose_name='type de salle')),
                ('info_sup', models.TextField(blank=True, null=True, verbose_name='Informations Supplémentaires')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.classe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_commande',
            field=models.DateField(default=datetime.datetime(2023, 8, 31, 22, 9, 31, 261358, tzinfo=datetime.timezone.utc), verbose_name='date de la commande'),
        ),
        migrations.CreateModel(
            name='ReservationSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(verbose_name='Date de debut')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.reservation', verbose_name='réservation')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.chambre', verbose_name='salle')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checkin', models.DateField(blank=True, null=True, verbose_name='Date de check-in')),
                ('date_checkout', models.DateField(blank=True, null=True, verbose_name='Date de check-out')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.chambre', verbose_name='chambre')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebergement.reservation', verbose_name='réservation')),
            ],
        ),
    ]
