# Generated by Django 4.2.4 on 2023-08-31 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_classe_service_serviceclasse'),
        ('hebergement', '0005_chambre_salle_reservation_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='services_inclus',
            field=models.ManyToManyField(to='core.service', verbose_name='services inclus'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_commande',
            field=models.DateField(default=datetime.datetime(2023, 8, 31, 22, 12, 11, 652374, tzinfo=datetime.timezone.utc), verbose_name='date de la commande'),
        ),
    ]
