# Generated by Django 4.2.4 on 2023-08-31 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0006_reservation_services_inclus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='statut',
            field=models.CharField(choices=[('L', 'Libre'), ('B', 'Reservation Brouillon'), ('C', 'Reservation Confirmée'), ('T', 'Reservation Terminée'), ('O', 'Check-out')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_commande',
            field=models.DateField(default=datetime.datetime(2023, 8, 31, 22, 19, 59, 855570, tzinfo=datetime.timezone.utc), verbose_name='date de la commande'),
        ),
    ]
