# Generated by Django 4.2.4 on 2023-09-01 10:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_personne_date_naissance'),
        ('hebergement', '0007_chambre_statut_alter_reservation_date_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='id',
        ),
        migrations.AddField(
            model_name='salle',
            name='service_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chambre',
            name='statut',
            field=models.CharField(choices=[('L', 'Libre'), ('B', 'Reservation Brouillon'), ('C', 'Reservation Confirmée'), ('T', 'Reservation Terminée'), ('O', 'Check-out'), ('N', 'Nettoyage'), ('M', 'Maintenance')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_commande',
            field=models.DateField(default=datetime.datetime(2023, 9, 1, 10, 29, 7, 451820, tzinfo=datetime.timezone.utc), verbose_name='date de la commande'),
        ),
    ]
