# Generated by Django 4.2.4 on 2023-09-01 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_typeservice_alter_service_type_and_more'),
        ('hebergement', '0009_alter_reservation_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_commande',
            field=models.DateField(default=datetime.datetime(2023, 9, 1, 16, 37, 3, 946235, tzinfo=datetime.timezone.utc), verbose_name='date de la commande'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='services_inclus',
            field=models.ManyToManyField(to='core.typeservice', verbose_name='services inclus'),
        ),
    ]
