# Generated by Django 4.2.4 on 2023-09-01 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0011_alter_reservation_date_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='statut',
            field=models.CharField(choices=[('L', 'Libre'), ('B', 'Reservation Brouillon'), ('C', 'Reservation Confirmée'), ('T', 'Reservation Terminée'), ('O', 'Check-out'), ('N', 'Nettoyage'), ('M', 'Maintenance')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_commande',
            field=models.DateField(default=datetime.datetime(2023, 9, 1, 17, 10, 5, 731695, tzinfo=datetime.timezone.utc), verbose_name='date de la commande'),
        ),
    ]
