# Generated by Django 4.2.4 on 2023-09-02 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0012_salle_statut_alter_reservation_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_commande',
            field=models.DateField(default=datetime.datetime(2023, 9, 2, 17, 6, 6, 433643, tzinfo=datetime.timezone.utc), verbose_name='date de la commande'),
        ),
    ]
