# Generated by Django 4.2.4 on 2023-09-02 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0013_alter_reservation_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_commande',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date de la commande'),
        ),
    ]
