# Generated by Django 4.2.4 on 2023-09-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0015_alter_reservation_services_inclus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chambre',
            old_name='statut',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='statut',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='salle',
            old_name='statut',
            new_name='status',
        ),
    ]
