# Generated by Django 4.2.4 on 2023-09-02 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0016_rename_statut_chambre_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=1000, verbose_name='désignation')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='a_travers',
            field=models.CharField(choices=[('S', 'La Réception (sur site)'), ('W', 'Le Site Web'), ('A', 'Une Agence'), ('O', 'Autres')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='chambre',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hebergement.section', verbose_name='section'),
        ),
    ]
