# Generated by Django 4.2.4 on 2023-09-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_personne_date_naissance'),
        ('hebergement', '0017_section_alter_reservation_a_travers_chambre_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='personne',
            field=models.ManyToManyField(blank=True, null=True, to='core.client', verbose_name='Liste des personnes'),
        ),
    ]
