# Generated by Django 4.2.4 on 2023-09-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0018_reservation_personne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='personne',
            new_name='personnes',
        ),
    ]
